### ISSUE TITLE
Melhoria na AbstractEntity: abstract toString e nome para português

### ISSUE THREAD

**Issue by rinaldodev** [rinaldodev/aplicacao-exemplo-quarkus#30]
Realizar duas pequenas melhorias na AbstractEntity:
- declarar o método toString como abstract, para forçar as entidades a implementá-lo.
- Mudar nome para AbstractEntidade, pois acredito que seja um termo utilizado o suficiente em português.

**Comment by jean-merelis** [comment]
Sugiro também utilizar o Lombok para gerar os getters, setters, equals, hashCode e o toString.
Avaliar se a anotação `@Data` é suficiente. A anotação `@EqualsAndHashCode` deve utilizar o campo id da entidade. `@EqualsAndHashCode(of = "id")`

**Comment by rinaldodev** [comment]
`@Data` me parece suficiente, desde que:
- seja sobrescrito o `@EqualsAndHashCode` utilizando as chaves naturais e no `of`, e apenas campos eager
- seja sobrescrito o `@ToString` contendo apenas campos não-lazy com preferencialmente com `callSuper=true` para incluir o ID

Com relação a utilizar chaves de negócios ao invés do ID para o equals e hashCode, fui convencido após algumas opiniões que achei muito bem embasadas, além da própria documentação do Hibernate. Segue:

- Documentação do Hibernate sugerindo equals e hashCode com chaves de negócio: https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/persistent-classes-equalshashcode.html

Outros:
- https://thoughts-on-java.org/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/
- https://vladmihalcea.com/hibernate-facts-equals-and-hashcode/
- https://stackoverflow.com/a/1638886

**Comment by jean-merelis** [comment]
Eu mencionei o id para equals e hashcode devido ao costume. pois sempre utilizo UUID como id, que é a abordagem que o Vlad Mihalcea mencionou em uma [resposta mais abaixo](https://stackoverflow.com/a/24460365) no stackoverflow.

Agora considerando a entidade Fruta, cuja chave de negócio é o nome, como fica a situação se o usuário precisar editar o nome, assumindo que ele possa incluir novas frutas, e eventualmente pode digitar o nome errado e precisa corrigir?

**Comment by rinaldodev** [comment]
Entendi. Bom, não tenho certeza, mas acho que usar uuid nessa aplicação não seria ideal, já que é meio polêmico se é melhor ou não, e principalmente no que diz respeito à performance do banco.
