### ISSUE TITLE
Retornar uma DTO direto da query do Panache/Hibernate

### ISSUE THREAD

**Issue by rinaldodev** [rinaldodev/aplicacao-exemplo-quarkus#6]
Algumas pessoas advogam que é melhor retornar uma DTO direto da query do JPA, apenas com as colunas necessárias para a funcionalidade. Acho que um exemplo disso seria interessante.

**Comment by jean-merelis** [comment]
Apenas minha opinião pessoal
Criar queries com colunas personalizadas JPA/Hibernate é dolorido.
ter que mapear usando @SqlResultSetMappings...
ter que criar construtores de acordo com as colunas da query e lembrar a ordem pois não é tipado...
fazer uso Criteria... isso dói

Por estes e outros motivos estou migrando para o jOOQ.

Mas será interessante ver exemplos deste tipo.

**Comment by rinaldodev** [comment]
Eu andei pensando nisso e acho que concordo. Acho que basta preencher apenas os campos solicitados na entidade, explicitando eles na query, e na hora que o Mapstruct for fazer o mapping e simplesmente vai ignorar o que estiver vazio.

**Comment by rinaldodev** [comment]
Bom, como a Issue #7 já atende essa necessidade, vou fechar esta aqui. Valeu!
